---
title: "01-convert-tax-data"
output: html_document
---

```{r}
library(tidyverse)
library(readxl)
library(glue)
library(janitor)
library(stringi)
source(here::here('cobb-scripts/00-functions.R'))

```

```{r}
input_folder <- here::here("data/cobb")
output_folder <- here::here("output/cobb")

keywords <- c("TX502") ## this contains the parcel id, address, FMV, owner 1 &2, address, total tax, appeal value, mill vals, exemptions, owner & situs address in detail (!) 

paths <- get_relevant_files(input_folder, keywords) %>% 
  filter(year != 2021) # this is because the 2021 year is already in a tabular format

## read in and clean data dictionaries
cobb_data <- paths %>%
  mutate(dictionary = map(dict_path, 
                          ~ read_excel(.x, skip = 5) %>% 
                            clean_cobb_dictionaries()
                          ))
  
for (year in cobb_data$year) {
  message("Processing: ", year)
  dict_file <- cobb_data$dict_path[which(cobb_data$year == year)]
  txt_file <- cobb_data$data_path[which(cobb_data$year == year)]

  cobb_dictionary <- read_excel(dict_file, skip = 5) %>% clean_cobb_dictionaries() 
  txt_lines <- readLines(txt_file)
  
  processed_lines <- process_lines(txt_lines, cobb_dictionary)
  processed_file_to_csv(processed_lines, cobb_dictionary, output_folder, txt_file, dict_file)
}
```

