name: cherokee
root-path: C:\Users\Nick\Documents\code\ga-tax-assessment\data\cherokee
var-map-path: C:\Users\Nick\Documents\code\ga-tax-assessment\input\var_maps\cherokee_var_map.csv
operations:
  merge-years:
    type: merge
    groups:
      - "2020"
      - "2021"
      - "2022"
    files:
      ".*d_real.*": cherokee
      ".*d_owner.*": cherokee
      ".*d_calcexemptions.*": cherokee
      ".*d_accsry.*": cherokee
    key:
      - parcel_id
      - tax_year
    join-type: outer
  append-years:
    type: append
    files:
      merge-years: default
output:
  path: cherokee-output
  formats:
    - csv

