name: Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests with coverage
      run: pytest --capture=no
    
    - name: Generate coverage badge
      run: coverage-badge -o .github/coverage.svg
    
    - name: Commit coverage badge
      uses: EndBug/add-and-commit@v7
      with:
        add: '.github/coverage.svg'
        message: 'Update coverage badge'